spring:
  datasource:
    url: jdbc:h2:mem:studentsdb
    driver-class-name: org.h2.Driver
    username: root
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
